name: PluginsMap CI

on:
  push:
    branches:
      - dev
      - master
      - rc
      - staging
      - build-test
      - omz
    paths:
      - 'scripts/pluginsMap.js'
      - '.github/workflows/plugins-map.yaml'
  pull_request:
    branches:
      - dev
      - master
      - rc
      - staging
      - omz
    paths:
      - 'scripts/pluginsMap.js'
      - '.github/workflows/plugins-map.yaml'

jobs:
  ui:
    runs-on: ubuntu-22.04

    steps:
      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.x

      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test' || github.ref == 'refs/heads/omz')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test' || github.ref == 'refs/heads/omz')
        run: |
          aws s3 cp scripts/pluginsMap.js s3://erxes-${GITHUB_REF#refs/heads/}-plugins
